[general]
home = "~/Workspace"
concurrency = 1
[general.env]
"GIT_SSH_COMMAND" = "ssh -o TcpKeepAlive=no -o ServerAliveInterval=10"

[platform.codeberg]
origin = false
domain = "codeberg.org"
user = "stepbrobd"

[platform.github]
origin = true
domain = "github.com"
user = "stepbrobd"

[platform.gitlab]
origin = false
domain = "gitlab.com"
user = "stepbrobd"

[platform.sourcehut]
origin = false
domain = "git.sr.ht"
user = "~stepbrobd"

## Personal
[repo."aoc"]
description = "advent of code"
visibility = "public"
archived = false

[repo."autopilot"]
description = "flake parts with autoloading"
visibility = "public"
archived = false

[repo."churn"]
description = "churn, baby, churn!"
visibility = "public"
archived = false

[repo."consistency-coq"]
description = "consistency semantics with coq"
visibility = "private"
archived = false

[repo."consistency-z3"]
description = "consistency semantics with z3"
visibility = "public"
archived = false

[repo."cv"]
description = "cv in typst with auto build and release"
visibility = "public"
archived = false

[repo."dotfiles"]
description = "yet another dotfiles repo with nix"
visibility = "public"
archived = false

[repo."finch"]
description = "hackzurich 2023: finch - a simple neural net framework and visualizer that uses genetic networks to train"
visibility = "public"
archived = false

[repo."homebrew-tap"]
description = "custom homebrew tap"
visibility = "public"
archived = false

[repo."icecream"]
description = "soft serve configs"
visibility = "public"
archived = true

[repo."metaprocessor"]
description = "metaprocessor, all-in-one data pipeline for mbientlab metawear series sensors"
visibility = "public"
archived = false

[repo."nixology"]
description = "all about nix"
visibility = "public"
archived = false

[repo."rkt"]
description = "learn a useful language"
visibility = "public"
archived = false

[repo."ruga"]
description = "ruby meets genetic algorithm"
visibility = "private"
archived = false

[repo."sentik"]
description = "hackmit 2022: sentik - live tweet sentiment analysis for traders"
visibility = "public"
archived = true

[repo."srd"]
description = "srd: (go) static race detector"
visibility = "public"
archived = false

[repo."stepbrobd"]
description = "just another profile readme"
visibility = "public"
archived = false

[repo."tailscale-acls"]
description = "tailscale access controls"
visibility = "public"
archived = false

[repo."tailscale-on-fly"]
description = "run a vpn service with global exit nodes with fly.io and tailscale"
visibility = "public"
archived = false

[repo."tailscale-on-openwrt"]
description = "brings tailscale to low powered openwrt devices"
visibility = "public"
archived = false

[repo."tbot"]
description = "teeebot..."
visibility = "private"
archived = false

[repo."yeh"]
description = "imap/smtp proxy for hey.com"
visibility = "public"
archived = false

[repo."ysun"]
description = "nix + deno + lume"
visibility = "public"
archived = false

## Forks
[repo."coq"]
description = "forked from coq/coq"
visibility = "public"
archived = false

[repo."crunchycli"]
description = "forked from crunchy-labs/crunchy-cli"
visibility = "public"
archived = true

[repo."deno2nix"]
description = "forked from sno2wman/deno2nix"
visibility = "public"
archived = false

[repo."figure"]
description = "forked from ruanyf/markdown-it-image-lazy-loading"
visibility = "public"
archived = false

[repo."go"]
description = "forked from golang/go"
visibility = "public"
archived = false

[repo."golink"]
description = "forked from tailscale/golink"
visibility = "public"
archived = false

[repo."homebrew-cask"]
description = "forked from homebrew/homebrew-cask"
visibility = "public"
archived = false

[repo."hopper"]
description = "forked from cybergenik/hopper"
visibility = "public"
archived = false

[repo."lean4"]
description = "forked from leanprover/lean4"
visibility = "public"
archived = false

[repo."lean4-nix"]
description = "forked from lenianiva/lean4-nix"
visibility = "public"
archived = false

[repo."ngipkgs"]
description = "forked from ngi-nix/ngipkgs"
visibility = "public"
archived = false

[repo."nix"]
description = "forked from nixos/nix"
visibility = "public"
archived = false

[repo."nixpkgs"]
description = "forked from nixos/nixpkgs"
visibility = "public"
archived = false

[repo."nixvim"]
description = "forked from nix-community/nixvim"
visibility = "public"
archived = false

[repo."nrok"]
description = "forked from isker/neogrok"
visibility = "public"
archived = false

[repo."osu"]
description = "forked from ppy/osu"
visibility = "public"
archived = false

[repo."soft-serve"]
description = "forked from charmbracelet/soft-serve"
visibility = "public"
archived = false

[repo."tailscale"]
description = "forked from tailscale/tailscale"
visibility = "public"
archived = false

[repo."tvix"]
description = "forked from tvlfyi/tvix"
visibility = "public"
archived = false

## Northeastern University
[repo."neu-cs-5010"]
description = "cs 5010 fall 2023 @ northeastern university"
visibility = "private"
archived = true

[repo."neu-cs-5200"]
description = "cs 5200 spring 2024 @ northeastern university"
visibility = "private"
archived = true

[repo."neu-cs-5800"]
description = "cs 5800 fall 2023 @ northeastern university"
visibility = "private"
archived = true

[repo."neu-cs-6410"]
description = "cs 6410 spring 2025 @ northeastern university"
visibility = "private"
archived = false

[repo."neu-cy-6740"]
description = "cy 6740 spring 2024 @ northeastern university"
visibility = "private"
archived = true

[repo."neu-cs-7400"]
description = "cs 7400 fall 2024 @ northeastern university"
visibility = "private"
archived = true

## University of Utah
[repo."uutah-cs-1410"]
description = "cs 1410 spring 2020 @ university of utah"
visibility = "private"
archived = true

[repo."uutah-cs-2420"]
description = "cs 2420 fall 2020 @ university of utah"
visibility = "private"
archived = true

[repo."uutah-cs-3011"]
description = "cs 3011 spring 2023 @ university of utah"
visibility = "private"
archived = true

[repo."uutah-cs-3500"]
description = "cs 3500 spring 2021 @ university of utah"
visibility = "private"
archived = true

[repo."uutah-cs-3505"]
description = "cs 3505 fall 2021 @ university of utah"
visibility = "private"
archived = true

[repo."uutah-cs-4150"]
description = "cs 4150 spring 2022 @ university of utah"
visibility = "private"
archived = true

[repo."uutah-cs-4400"]
description = "cs 4400 fall 2021 @ university of utah"
visibility = "private"
archived = true

[repo."uutah-cs-4440"]
description = "cs 4440 spring 2022 @ university of utah"
visibility = "private"
archived = true

[repo."uutah-cs-4480"]
description = "cs 4480 spring 2022 @ university of utah"
visibility = "private"
archived = true

[repo."uutah-cs-4790"]
description = "cs 4790 spring 2023 @ university of utah"
visibility = "private"
archived = true

[repo."uutah-cs-6110"]
description = "cs 6110 spring 2023 @ university of utah"
visibility = "private"
archived = true

[repo."uutah-cs-6340"]
description = "cs 6340 fall 2022 @ university of utah"
visibility = "private"
archived = true

[repo."uutah-cs-6450"]
description = "cs 6450 fall 2022 @ university of utah"
visibility = "private"
archived = true

[repo."uutah-cs-6490"]
description = "cs 6490 spring 2023 @ university of utah"
visibility = "private"
archived = true
