[general]
home = "~/Workspace"

[general.env]
"GIT_SSH_COMMAND" = "ssh -o TcpKeepAlive=no -o ServerAliveInterval=10"

[platform.codeberg]
origin = false
domain = "codeberg.org"
user = "stepbrobd"

[platform.github]
origin = true
domain = "github.com"
user = "stepbrobd"

[platform.gitlab]
origin = false
domain = "gitlab.com"
user = "stepbrobd"

[platform.sourcehut]
origin = false
domain = "git.sr.ht"
user = "~stepbrobd"

[platform.inria]
origin = false
domain = "gitlab.inria.fr"
user = "yisun"

## Personal
[repo."aoc"]
description = "advent of code"
visibility = "public"
archived = false

[repo."autopilot"]
description = "flake parts with autoloading"
visibility = "public"
archived = false

[repo."churn"]
description = "churn, baby, churn!"
visibility = "public"
archived = false

[repo."consistency-coq"]
description = "consistency semantics with coq"
visibility = "private"
archived = false

[repo."consistency-z3"]
description = "consistency semantics with z3"
visibility = "private"
archived = false

[repo."cv"]
description = "cv in typst with auto build and release"
visibility = "public"
archived = false

[repo."dotfiles"]
description = "yet another dotfiles repo with nix"
visibility = "public"
archived = false

[repo."finch"]
description = "hackzurich 2023: finch - a simple neural net framework and visualizer that uses genetic networks to train"
visibility = "public"
archived = false

[repo."fosdem"]
description = "fosdem '26 stuff"
visibility = "public"
archived = false

[repo."homebrew-tap"]
description = "custom homebrew tap"
visibility = "public"
archived = false

[repo."icecream"]
description = "soft serve configs"
visibility = "public"
archived = true

[repo."metaprocessor"]
description = "metaprocessor, all-in-one data pipeline for mbientlab metawear series sensors"
visibility = "public"
archived = false

[repo."miroir"]
description = "repo manager wannabe?"
visibility = "public"
archived = false

[repo."mono"]
description = "the only source of truth"
visibility = "private"
archived = false

[repo."multikernel"]
description = "multikernel test"
visibility = "public"
archived = false

[repo."nixology"]
description = "all about nix"
visibility = "public"
archived = false

[repo."nord.yazi"]
description = "nordic yazi"
visibility = "public"
archived = false

[repo."rkt"]
description = "learn a useful language"
visibility = "public"
archived = true

[repo."router"]
description = "simple and declarative nixos router"
visibility = "public"
archived = false

[repo."ruga"]
description = "ruby meets genetic algorithm"
visibility = "private"
archived = false

[repo."sentik"]
description = "hackmit 2022: sentik - live tweet sentiment analysis for traders"
visibility = "public"
archived = true

[repo."srd"]
description = "srd: (go) static race detector"
visibility = "public"
archived = false

[repo."stepbrobd"]
description = "just another profile readme"
visibility = "public"
archived = false

[repo."tailscale-acls"]
description = "tailscale access controls"
visibility = "public"
archived = false

[repo."tailscale-on-fly"]
description = "run a vpn service with global exit nodes with fly.io and tailscale"
visibility = "public"
archived = false

[repo."tailscale-on-openwrt"]
description = "brings tailscale to low powered openwrt devices"
visibility = "public"
archived = false

[repo."tbot"]
description = "teeebot..."
visibility = "private"
archived = false

[repo."x"]
description = "all the weird stuff goes here"
visibility = "public"
archived = false

[repo."yeh"]
description = "imap/smtp proxy for hey.com"
visibility = "public"
archived = false

[repo."ysun"]
description = "nix // yocaml"
visibility = "public"
archived = false

## Forks
[repo."cfspeedtest"]
description = "forked from code-inflation/cfspeedtest"
visibility = "public"
archived = false

[repo."coq"]
description = "forked from coq/coq"
visibility = "public"
archived = false

[repo."coq-nix-toolbox"]
description = "forked from rocq-community/coq-nix-toolbox"
visibility = "public"
archived = false

[repo."crunchycli"]
description = "forked from crunchy-labs/crunchy-cli"
visibility = "public"
archived = true

[repo."deno2nix"]
description = "forked from sno2wman/deno2nix"
visibility = "public"
archived = false

[repo."disko"]
description = "forked from nix-community/disko"
visibility = "public"
archived = false

[repo."dolmen"]
description = "forked from gbury/dolmen"
visibility = "public"
archived = false

[repo."figure"]
description = "forked from ruanyf/markdown-it-image-lazy-loading"
visibility = "public"
archived = false

[repo."flavors"]
description = "forked from yazi-rs/flavors"
visibility = "public"
archived = false

[repo."go"]
description = "forked from golang/go"
visibility = "public"
archived = false

[repo."golink"]
description = "forked from tailscale/golink"
visibility = "public"
archived = false

[repo."gre-nug"]
description = "forked from gre-nug/gre-nug"
visibility = "public"
archived = false

[repo."homebrew-cask"]
description = "forked from homebrew/homebrew-cask"
visibility = "public"
archived = false

[repo."hopper"]
description = "forked from cybergenik/hopper"
visibility = "public"
archived = false

[repo."kanidm"]
description = "forked from kanidm/kanidm"
visibility = "public"
archived = false

[repo."kapack"]
description = "forked from oar-team/nur-kapack"
visibility = "public"
archived = false

[repo."kumify"]
description = "forked from denzha24/kumify"
visibility = "public"
archived = false

[repo."lean4"]
description = "forked from leanprover/lean4"
visibility = "public"
archived = false

[repo."lean4-nix"]
description = "forked from lenianiva/lean4-nix"
visibility = "public"
archived = false

[repo."linux"]
description = "forked from torvalds/linux"
visibility = "public"
archived = false

[repo."ngipkgs"]
description = "forked from ngi-nix/ngipkgs"
visibility = "public"
archived = false

[repo."nix"]
description = "forked from nixos/nix"
visibility = "public"
archived = false

[repo."nix-darwin"]
description = "forked from lnl7/nix-darwin"
visibility = "public"
archived = false

[repo."nixos-raspberrypi"]
description = "forked from nvmd/nixos-raspberrypi"
visibility = "public"
archived = false

[repo."nixpkgs"]
description = "forked from nixos/nixpkgs"
visibility = "public"
archived = false

[repo."nixpkgs-review-gha"]
description = "forked from defelo/nixpkgs-review-gha"
visibility = "public"
archived = false

[repo."nixvim"]
description = "forked from nix-community/nixvim"
visibility = "public"
archived = false

[repo."nrok"]
description = "forked from isker/neogrok"
visibility = "public"
archived = false

[repo."osu"]
description = "forked from ppy/osu"
visibility = "public"
archived = false

[repo."shiki"]
description = "forked from furiouzz/lume_shiki"
visibility = "public"
archived = false

[repo."soft-serve"]
description = "forked from charmbracelet/soft-serve"
visibility = "public"
archived = false

[repo."raven"]
description = "forked from raven-ml/raven"
visibility = "public"
archived = false

[repo."ring"]
description = "forked from muhokama/ring"
visibility = "public"
archived = false

[repo."souin"]
description = "forked from darkweak/souin"
visibility = "public"
archived = false

[repo."sora"]
description = "forked from cranci1/sora"
visibility = "public"
archived = false

[repo."tailscale"]
description = "forked from tailscale/tailscale"
visibility = "public"
archived = false

[repo."tvix"]
description = "forked from tvlfyi/tvix"
visibility = "public"
archived = false

[repo."verus"]
description = "forked from verus-lang/verus"
visibility = "public"
archived = false
